import { useState } from 'react'
import {
  Badge, Button, Checkbox, FluentProvider, Input, Link, MessageBar,
  MessageBarBody, Select, Tab, TabList, webLightTheme,
} from '@fluentui/react-components'
import {
  AddRegular, AppsRegular, ArrowDownloadRegular,
  CheckmarkCircleRegular, ChevronDownRegular, DeleteRegular,
  DismissRegular, EditRegular, FilterRegular, HomeRegular,
  InfoRegular, NavigationRegular, PaymentRegular, SearchRegular,
  SettingsRegular, WarningRegular,
} from '@fluentui/react-icons'
import './App.css'

type View = 'products' | 'contracts' | 'workspace' | 'cart' | 'orderSuccess' | 'orders' | 'orderDetail' | 'reservations' | 'reservationCreate' | 'reservationSuccess'
type Drawer = 'none' | 'products' | 'stepups' | 'bulk' | 'split' | 'contractDetails' | 'manageContracts'
type Version = 'v1' | 'v2'
 | 'v3'

type ProductRow = {
  id: string; name: string; icon: string; type: string; prior: number; additional: number;
  country: string; billing: string; unit: number; source: string; upgrade?: boolean
}

type CatalogueProduct = ProductRow & { family: string; offering: string; description: string }

const contracts = [
  ['6021478465', 'Proseware, Inc.', 'Oslo, Norway', 'Aug 2, 2025 – Aug 31, 2025', 'Compliant'],
  ['6878820157', 'Fourth Coffee', 'Munich, Germany', 'Ended Apr 30, 2025', 'Non compliant'],
  ['6579421301', 'Contoso Pharmaceuticals', 'Seattle, United States', 'Ends Feb 28, 2025', 'Compliant'],
  ['526824010', 'Liberty’s Hospital Skull & Cry', 'Moscow, Russia', 'Aug 2, 2025 – Aug 31, 2025', 'Compliant'],
  ['584975650', 'School of Fine Art', 'Moscow, Russia', 'Aug 2, 2025 – Aug 31, 2025', 'Compliant'],
  ['4273658003', 'Consolidated Messenger', 'Bergen, Norway', 'Aug 2, 2025 – Aug 31, 2025', 'Compliant'],
  ['4207651478', 'Fabrikam, Inc.', 'Basel, Switzerland', 'Aug 2, 2025 – Aug 31, 2025', 'Compliant'],
  ['3745789656', 'Proseware, Inc.', 'Australia', 'Sep 1, 2025', 'Non compliant'],
]

const initialProducts: ProductRow[] = [
  { id: 'NKA-00002', name: '10 year auditlog retention add on', icon: 'ms', type: 'True-up', prior: 200, additional: 0, country: 'United states', billing: 'Annual', unit: 22.75, source: 'CPS: 98765.002', upgrade: true },
  { id: '076-01776', name: 'Advanced data residency', icon: 'ms', type: 'True-up', prior: 300, additional: 0, country: 'United states', billing: 'Annual', unit: 5.5, source: 'CPS: 98765.002', upgrade: true },
  { id: 'TKB-00123', name: 'Enhanced security features', icon: 'office', type: 'True-up', prior: 450, additional: 0, country: 'United states', billing: 'Annual', unit: 119.6, source: 'CPS: 15112.003' },
  { id: 'PL7-04589', name: 'Real-time analytics dashboard', icon: 'office', type: 'True-up', prior: 120, additional: 0, country: 'United states', billing: 'Annual', unit: 25, source: 'CPS: 98765.002' },
  { id: 'QR3-08654', name: 'Automated compliance reporting', icon: 'ms', type: 'True-up', prior: 75, additional: 0, country: 'United states', billing: 'Annual', unit: 8, source: 'CPS: 98765.002' },
  { id: 'XF2-00234', name: 'Multi-factor authentication', icon: 'ms', type: 'True-up', prior: 220, additional: 0, country: 'United states', billing: 'Annual', unit: 9.4, source: 'CPS: 15112.003', upgrade: true },
  { id: 'MN9-11234', name: 'User activity monitoring', icon: 'office', type: 'True-up', prior: 600, additional: 0, country: 'United states', billing: 'Annual', unit: 15.25, source: 'CPS: 98765.002' },
  { id: 'YZ1-00987', name: 'Data encryption at rest', icon: 'office', type: 'True-up', prior: 90, additional: 0, country: 'United states', billing: 'Annual', unit: 66.8, source: 'CPS: 15112.003', upgrade: true },
]

const catalogueProducts: CatalogueProduct[] = [
  { id: 'AAA-06269', name: 'Microsoft 365 E3', icon: 'ms', family: 'Microsoft 365', offering: 'Enterprise', description: 'Productivity, security, and compliance services.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 36, source: 'CPS: 98765.002', upgrade: true },
  { id: 'AAA-10732', name: 'Microsoft 365 E5', icon: 'ms', family: 'Microsoft 365', offering: 'Enterprise', description: 'Advanced security, analytics, voice, and compliance.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 57, source: 'CPS: 98765.002' },
  { id: 'AAA-22348', name: 'Microsoft Teams Premium', icon: 'ms', family: 'Microsoft Teams', offering: 'Enterprise', description: 'Intelligent meetings and advanced meeting protection.', type: 'Add-on', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 10, source: 'CPS: 15112.003' },
  { id: 'CFQ7TTC0LH18', name: 'Power BI Pro', icon: 'office', family: 'Power BI', offering: 'Enterprise', description: 'Share reports and collaborate with business analytics.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 14, source: 'CPS: 98765.002' },
  { id: 'CFQ7TTC0LH1T', name: 'Power Apps Premium', icon: 'office', family: 'Power Platform', offering: 'Enterprise', description: 'Build and run custom business applications.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 20, source: 'CPS: 98765.002' },
  { id: 'CFQ7TTC0LH2H', name: 'Power Automate Premium', icon: 'office', family: 'Power Platform', offering: 'Enterprise', description: 'Automate cloud and desktop workflows.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 15, source: 'CPS: 15112.003' },
  { id: 'AAA-55129', name: 'Dynamics 365 Sales Enterprise', icon: 'ms', family: 'Dynamics 365', offering: 'Enterprise', description: 'Sales automation and relationship intelligence.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 105, source: 'CPS: 15112.003' },
  { id: 'AAA-51234', name: 'Microsoft Defender for Office 365 Plan 2', icon: 'ms', family: 'Security', offering: 'Enterprise', description: 'Threat investigation and automated response.', type: 'Add-on', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 5, source: 'CPS: 98765.002' },
  { id: 'AAA-73004', name: 'Microsoft Project Plan 3', icon: 'office', family: 'Project', offering: 'Enterprise', description: 'Project scheduling and resource management.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 30, source: 'CPS: 98765.002' },
  { id: 'AAA-13254', name: 'Microsoft Visio Plan 2', icon: 'office', family: 'Visio', offering: 'Enterprise', description: 'Professional diagramming for desktop and web.', type: 'Online subscription', prior: 0, additional: 1, country: 'United states', billing: 'Annual', unit: 15, source: 'CPS: 15112.003' },
]

const cartRows = [
  ['Planner 2025 Enterprise Pack Per User', 'AIA-78352', '263', '100', '363', '$22.75', '$2,275.00'],
  ['Power Apps Premium Sub Per User', 'AUG-67987', 'Does not apply', '45', '45', '$43.50', '$1,783.92'],
  ['Power Automate Premium Sub Per User', '1O4-00001', '20', '33', '53', '$85.00', '$3,876.00'],
  ['Power BI Pro Pack Enterprise Per User 2025', 'SEJ-00002', '150', '84', '234', '$106.44', '$8,940.96'],
  ['Stream and video essentials 2025', '3T6-78789', '550', '183', '733', '$242.31', '$44,342.73'],
  ['Teams Enterprise 2025 Per User', 'AAA-26962', '125', '35', '160', '$54.90', '$1,921.50'],
  ['Visio pack 2025 Enterprise', 'AAI-99292', '50', '21', '71', '$133.30', '$2,799.30'],
]

const reservationRows = [
  ['15101475420941', 'HR Department', 'June 20, 2025', 'July 01, 2025', 'Active', 'Pending', 'Sheffield Kelly', '-', 'Cancel'],
  ['12345678901234', 'Reservation name', 'June 20, 2025', 'July 01, 2025', 'Active', 'Pending', 'Adam Smith', '-', 'Cancel'],
  ['78964567980234', '', 'Apr 20, 2025', 'May 01, 2025', 'Active', 'Pending', 'Sheffield Kelly', '-', 'Cancel'],
  ['54683902547863', '', 'June 20, 2023', 'June 30, 2025', 'Expired', 'Reconciled', 'Allen White', 'PO83643, PO37612', '-'],
  ['09265879062567', '', 'June 20, 2023', 'July 01, 2025', 'Active', 'Partially reconciled', 'Nobu Galloway', 'PO83643', '-'],
  ['89395467893904', '', 'June 20, 2023', 'June 30, 2025', 'Pending', 'Pending', 'Arvind Thakre', '-', '-'],
  ['89395467893904', '', 'June 20, 2023', 'June 30, 2025', 'Failed', '-', 'Arvind Thakre', '-', '-'],
  ['89395467893904', '', 'June 20, 2023', 'June 30, 2025', 'Canceled', '-', 'Arvind Thakre', '-', '-'],
]

const navItems = ['Home', 'Users', 'Devices', 'Groups', 'Roles', 'Resources', 'Billing', 'Purchase services', 'Your products', 'Licenses', 'Bills & payments', 'Payment methods', 'Billing accounts', 'Support', 'Settings', 'Setup', 'Reports', 'Health']
const v3NavItems = ['Overview', 'Orders', 'Reservations', 'Contracts']

function Mark({ type = 'ms' }: { type?: string }) {
  return type === 'office' ? <span className="office-mark">◐</span> : <span className="ms-mark"><i /><i /><i /><i /></span>
}

function AdminShell({ view, setView, version, setVersion, children }: { view: View; setView: (view: View) => void; version: Version; setVersion: (version: Version) => void; children: React.ReactNode }) {
  const expanded = version !== 'v1' || view === 'products'
  const shellNavItems = version === 'v3' ? v3NavItems : navItems
  const navigateV3 = (item: string) => {
    if (item === 'Overview') setView('products')
    else if (item === 'Orders') setView('orders')
    else if (item === 'Reservations') setView('reservations')
    else if (item === 'Contracts') setView('contracts')
  }
  return <div className={`admin-shell${version === 'v2' ? ' admin-shell-v2' : version === 'v3' ? ' admin-shell-v2 admin-shell-v3' : ''}`}>
    <header className="admin-top"><Button appearance="subtle" icon={<AppsRegular />} aria-label="App launcher" /><strong>{version === 'v3' ? 'Order operations' : 'Microsoft 365 admin center'}</strong><label className="version-switcher"><span>Version</span><Select aria-label="Experience version" value={version} onChange={(_, data) => setVersion(data.value as Version)}><option value="v1">V1</option><option value="v2">V2</option><option value="v3">V3</option></Select></label><div className="global-search"><SearchRegular /><input aria-label="Global search" placeholder={version === 'v3' ? 'Search orders, contracts, products, or customers' : 'Search for users, groups, settings, and actions'} /></div><div className="top-tools"><span>▣</span><span>▯</span><SettingsRegular /><span>?</span><span className="user-dot">AL</span></div></header>
    <div className="admin-body"><aside className={expanded ? 'admin-nav expanded' : 'admin-nav compact'}><Button appearance="subtle" icon={<NavigationRegular />} aria-label="Navigation" />{shellNavItems.map((item, index) => {
      const child = version !== 'v3' && index >= 7 && index <= 12
      const active = version === 'v3' ? (item === 'Overview' && view === 'products') || (item === 'Orders' && ['orders', 'orderDetail'].includes(view)) || (item === 'Reservations' && ['reservations', 'reservationCreate', 'reservationSuccess'].includes(view)) || (item === 'Contracts' && ['contracts', 'workspace', 'cart', 'orderSuccess'].includes(view)) : item === 'Your products'
      return <button key={item} type="button" className={`${active ? 'active' : ''} ${child ? 'nav-child' : ''}`} onClick={() => version === 'v3' ? navigateV3(item) : item === 'Your products' && setView('products')}><span className="nav-symbol">{index === 0 ? <HomeRegular /> : index === 1 && version === 'v3' ? <PaymentRegular /> : index === 6 && version !== 'v3' ? <PaymentRegular /> : index === 8 && version !== 'v3' ? <AppsRegular /> : '○'}</span>{expanded && <span>{item}</span>}{expanded && version !== 'v3' && [1,2,3,5,6,13,14,16,17].includes(index) && <ChevronDownRegular />}</button>})}{version !== 'v3' && <div className="admin-centers">{expanded && <b>Admin centers</b>}<button type="button"><span className="nav-symbol">◇</span>{expanded && 'Security'}</button><button type="button"><span className="nav-symbol">◇</span>{expanded && 'Compliance'}</button></div>}</aside><main className="portal-main">{version !== 'v1' && <WorkflowGuide view={view} />}{children}</main></div>
  </div>
}

function WorkflowGuide({ view }: { view: View }) {
  const orderSteps: View[] = ['contracts', 'workspace', 'cart', 'orderSuccess']
  const reservationSteps: View[] = ['reservationCreate', 'reservationSuccess']
  const steps = orderSteps.includes(view) ? ['Contract', 'Products', 'Review', 'Submitted'] : reservationSteps.includes(view) ? ['Services', 'Confirmation'] : null
  if (!steps) return null
  const current = orderSteps.includes(view) ? orderSteps.indexOf(view) : reservationSteps.indexOf(view)
  return <div className="workflow-guide" aria-label="Workflow progress"><div><span className="workflow-label">{orderSteps.includes(view) ? 'Create order' : 'New reservation'}</span><strong>{steps[current]}</strong></div><ol>{steps.map((step, index) => <li key={step} className={index < current ? 'complete' : index === current ? 'current' : ''}><span>{index < current ? '✓' : index + 1}</span>{step}</li>)}</ol></div>
}

function Breadcrumb({ items }: { items: string[] }) { return <div className="breadcrumbs">Home {items.map(item => <span key={item}>› {item}</span>)}</div> }

function V2Summary({ items }: { items: { value: string; label: string; tone?: 'positive' | 'attention' }[] }) {
  return <div className="v2-summary" aria-label="At a glance">{items.map(item => <div key={item.label} className={item.tone ? `summary-${item.tone}` : ''}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div>
}

function V3OrderHub({ go }: { go: (view: View) => void }) {
    return <div className="v3-hub">
      <header className="v3-hero"><div><span className="v3-eyebrow">ORDER OPERATIONS</span><h1>Good morning, Alex</h1><p>Place new orders, resolve exceptions, and track fulfillment from one workspace.</p></div><div className="v3-hero-actions"><Button appearance="primary" icon={<AddRegular />} onClick={() => go('contracts')}>Create order</Button><Button icon={<AddRegular />} onClick={() => go('reservationCreate')}>New reservation</Button></div></header>
      <section className="v3-pulse" aria-label="Order pulse"><div><span>Open orders</span><strong>24</strong><small>6 need action</small></div><div><span>In fulfillment</span><strong>18</strong><small>On track</small></div><div><span>Draft value</span><strong>$428K</strong><small>Across 7 drafts</small></div><div><span>Reservations</span><strong>8</strong><small>2 reconcile soon</small></div></section>
      <div className="v3-grid"><section className="v3-panel v3-orders"><div className="v3-panel-head"><div><span className="v3-eyebrow">WORK QUEUE</span><h2>Orders requiring attention</h2></div><Button appearance="subtle" onClick={() => go('orders')}>View all orders</Button></div><div className="v3-order-list"><button type="button" onClick={() => go('orderDetail')}><span className="v3-order-id">PO83644</span><span><b>Fourth Coffee</b><small>Contract 6878820157</small></span><Status state="In review" /><span className="v3-value">$86,420<small>Updated 2h ago</small></span></button><button type="button" onClick={() => go('orderDetail')}><span className="v3-order-id">PO83645</span><span><b>Contoso Pharmaceuticals</b><small>Contract 6579421301</small></span><Status state="Failed" /><span className="v3-value">$42,180<small>Payment issue</small></span></button><button type="button" onClick={() => go('orderDetail')}><span className="v3-order-id">PO83646</span><span><b>Fabrikam, Inc.</b><small>Contract 4207651478</small></span><Status state="In review" /><span className="v3-value">$118,760<small>Approval pending</small></span></button></div></section>
        <aside className="v3-panel v3-actions"><div className="v3-panel-head"><div><span className="v3-eyebrow">NEXT BEST ACTION</span><h2>Keep work moving</h2></div></div><button type="button" onClick={() => go('contracts')}><WarningRegular /><span><b>2 contracts need attention</b><small>Resolve compliance before ordering</small></span><ChevronDownRegular /></button><button type="button" onClick={() => go('reservations')}><InfoRegular /><span><b>Reconcile 2 reservations</b><small>Due within the next 14 days</small></span><ChevronDownRegular /></button><button type="button" onClick={() => go('orders')}><CheckmarkCircleRegular /><span><b>Review 6 submitted orders</b><small>Confirm status with customers</small></span><ChevronDownRegular /></button></aside>
        <section className="v3-panel v3-contracts"><div className="v3-panel-head"><div><span className="v3-eyebrow">CONTRACTS</span><h2>Ready to order</h2></div><Button appearance="subtle" onClick={() => go('contracts')}>Browse contracts</Button></div><div className="v3-contract-row">{contracts.slice(0,3).map(row => <button key={row[0]} type="button" onClick={() => go('contracts')}><span><b>{row[1]}</b><small>{row[0]} · {row[2]}</small></span><span className="v3-contract-status"><i />Ready</span></button>)}</div></section>
      </div>
    </div>
}

function ProductsPage({ go }: { go: (view: View) => void }) {
  return <div className="wide-page"><Breadcrumb items={['Your products']} /><h1>Your products</h1><p className="intro">These are products owned by your organization that were bought from Microsoft or 3rd-party providers. Select a product to manage product and billing settings or assign licenses.</p><V2Summary items={[{ value: '8', label: 'Volume contracts' }, { value: '6', label: 'Management tools' }, { value: '2', label: 'Contracts need attention', tone: 'attention' }]} /><TabList defaultSelectedValue="volume"><Tab value="products">Products</Tab><Tab value="mpsa">MPSA products</Tab><Tab value="volume">Volume licensing</Tab><Tab value="benefits">Benefits</Tab></TabList>
    <div className="product-home-grid"><InfoSection title="Downloads and keys" text="Find keys to the contracts and download details here." links={['Learn more about downloading software', 'Learn more about viewing keys']} action="View downloads and keys" /><InfoSection title="Contracts" text="See a list of the contracts that have been assigned to you." links={['Learn more about contracts']} action="View contracts" /><InfoSection title="Role assignments" text="Assign users to contracts in your domain, you can now add them manually. Manage users or edit their roles." action="Manage VL role assignments" /><InfoSection title="Transactions" text="See the statuses of all orders your organization has bought or reserved." links={['Learn more about orders', 'Learn more about order creation']} action="Create order" secondary="View orders" onPrimary={() => go('contracts')} onSecondary={() => go('orders')} /><InfoSection title="Reservations" text="Make new reservations for online services or manage existing reservations." links={['Learn more about reservations']} action="Reserve new online services" secondary="View reservations" onPrimary={() => go('reservationCreate')} onSecondary={() => go('reservations')} /><InfoSection title="Preferences" text="Manage e-mail preferences for notifications and alerts. Administrators can manage future administrator role inheritance where applicable." links={['Edit preferences']} /></div>
  </div>
}

function InfoSection({ title, text, links = [], action, secondary, onPrimary, onSecondary }: { title: string; text: string; links?: string[]; action?: string; secondary?: string; onPrimary?: () => void; onSecondary?: () => void }) {
  return <section className="info-section"><h2>{title}</h2><p>{text}</p>{links.map(link => <Link key={link}>{link}</Link>)}<div className="info-actions">{action && <Button appearance={onPrimary ? 'primary' : 'secondary'} onClick={onPrimary}>{action}</Button>}{secondary && <Button onClick={onSecondary}>{secondary}</Button>}</div></section>
}

function ContractsPage({ go }: { go: (view: View) => void }) {
  const [selected, setSelected] = useState(contracts[0][0])
  const selectedRow = contracts.find(row => row[0] === selected)
  return <div className="split-page"><div className="split-primary"><Breadcrumb items={['Your products', 'Volume licensing', 'Select contract']} /><h1>Select contract to create order</h1><p className="intro">To create an order, first choose the contract. We’ll show you which licenses are available based on the eligible agreements.</p><div className="filter-row"><span>Filters:</span><Badge appearance="tint">Organization: All</Badge><Badge appearance="tint">Location: All</Badge><Badge appearance="tint">Upcoming anniversary: All</Badge><Badge appearance="tint">Status: All</Badge><Button appearance="subtle" icon={<FilterRegular />}>Add filter</Button><Input size="small" contentBefore={<SearchRegular />} placeholder="Search" /></div><table className="fluent-table"><thead><tr><th></th><th>License ID ↑</th><th>Organization</th><th>Location</th><th>Compliance window</th><th>Upcoming anniversary</th><th>Status</th></tr></thead><tbody>{contracts.map(row => <tr key={row[0]} className={selected === row[0] ? 'selected' : ''} onClick={() => setSelected(row[0])}><td><Checkbox checked={selected === row[0]} aria-label={`Select ${row[0]}`} /></td><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3].includes('Ended') ? <span className="window"><i /><i /><i /> {row[3]}</span> : row[3]}</td><td>Sep 1, 2025</td><td>{row[4] === 'Compliant' ? row[4] : <span className="warning-text"><WarningRegular /> {row[4]}</span>}</td></tr>)}</tbody></table></div><aside className="context-pane">{!selectedRow ? <div className="context-empty"><InfoRegular /><p>Select a contract to start creating an order</p></div> : <><h2>License ID - {selectedRow[0]}</h2>{selectedRow[4] === 'Non compliant' ? <><MessageBar intent="error"><MessageBarBody>Looks like this contract is out of compliance for the prior year. Please update the contract before creating an order.</MessageBarBody></MessageBar><h3>Compliance Action Required</h3><p>To remain compliant, please take one of the following actions:</p><ul><li>Place a compliance order</li><li>Submit an update statement</li><li>Update your contract details</li></ul><div className="blocked"><WarningRegular /><p>Cannot create an order as the contract is non-compliant</p></div></> : <><h3>Pending actions</h3><p>There are 185 licenses pending reconciliation in this contract. Create an order to reconcile the reservations.</p><Link>View more about this</Link><h3>Select order type</h3><h4>New</h4><p>A new or midterm order allows you to add new licenses, adjust your current ones or reconcile reservations.</p><Button appearance="primary" onClick={() => go('workspace')}>Create order</Button><h4>Compliance</h4><p>To stay compliant with your licensing agreement, use this option to submit your yearly compliance order.</p><Button appearance="primary" onClick={() => go('workspace')}>Create compliance order</Button></>}</>}</aside></div>
}

function WorkspacePage({ go }: { go: (view: View) => void }) {
  const [rows, setRows] = useState(initialProducts)
  const [selected, setSelected] = useState<string[]>([])
  const [drawer, setDrawer] = useState<Drawer>('none')
  const total = rows.reduce((sum, row) => sum + row.additional * row.unit, 0)
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const updateQty = (id: string, value: number) => setRows(current => current.map(row => row.id === id ? { ...row, additional: value } : row))
  return <div className="work-page"><Breadcrumb items={['Your products', 'Volume licensing', 'Select contract', 'Create order']} /><h1>Create Midterm Order For License ID- <Link>7890567890</Link></h1><p className="intro">Select products from the list below. You can also search for products by SKU or product name, filter by CPS products or products from your order history.</p><TabList defaultSelectedValue="all"><Tab value="all">All products</Tab><Tab value="reconciliations">Reconciliations</Tab></TabList><div className="command-row"><Button appearance="subtle" icon={<AddRegular />} onClick={() => setDrawer('products')}>Add new products from catalogue</Button><Button appearance="subtle" icon={<EditRegular />} disabled={!selected.length} onClick={() => setDrawer('bulk')}>Edit</Button><Button appearance="subtle" icon={<DeleteRegular />} disabled={!selected.length} onClick={() => setRows(current => current.filter(row => !selected.includes(row.id)))}>Delete</Button></div><div className="filter-row left"><span>Filter:</span><Badge appearance="tint">View list by: <b>Previously ordered products</b></Badge><Badge appearance="tint">Product type: <b>All</b></Badge><Button appearance="subtle" icon={<FilterRegular />}>Add filter</Button><span className="table-spacer" /><span>{rows.length} items</span><Input size="small" contentBefore={<SearchRegular />} placeholder="Search" /></div><ProductTable rows={rows} selected={selected} toggle={toggle} updateQty={updateQty} onUpgrade={() => setDrawer('stepups')} /><div className="sticky-actions"><Button appearance="primary" disabled={total === 0} onClick={() => go('cart')}>Go to cart</Button><Button>Save as draft</Button><Button onClick={() => go('contracts')}>Back</Button><div className="estimated">Total estimated amount ({rows.filter(row => row.additional).length} items): <b>${total.toLocaleString(undefined, { minimumFractionDigits: 2 })}</b></div></div><SideDrawer drawer={drawer} close={() => setDrawer('none')} selectedCount={selected.length} onApply={() => { setRows(current => current.map(row => selected.includes(row.id) ? { ...row, additional: Math.max(row.additional, 25), country: 'Switzerland' } : row)); setDrawer('none') }} /></div>
}

function ProductTable({ rows, selected, toggle, updateQty, onUpgrade }: { rows: ProductRow[]; selected: string[]; toggle: (id: string) => void; updateQty: (id: string, value: number) => void; onUpgrade: () => void }) {
  return <div className="table-scroll"><table className="fluent-table product-table"><thead><tr><th><Checkbox /></th><th>Item name ↓</th><th>Part number</th><th>Product type</th><th>Upgrade</th><th>Prior quantity</th><th>Additional quantity</th><th>Usage country</th><th>Usage start date</th><th>Coverage period</th><th>Billing frequency</th><th>Unit price (Source)</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className={selected.includes(row.id) ? 'selected' : ''}><td><Checkbox checked={selected.includes(row.id)} onChange={() => toggle(row.id)} /></td><td><span className="product-name"><Mark type={row.icon} /><b>{row.name}</b></span></td><td>{row.id}</td><td>{row.type}<small>Online subscription</small></td><td>{row.upgrade ? <Link onClick={onUpgrade}>Available</Link> : '-'}</td><td>{row.prior}</td><td><Input size="small" type="number" value={String(row.additional)} onChange={(_, data) => updateQty(row.id, Number(data.value))} /></td><td>{row.country}</td><td>Jan 01, 2025</td><td>Jan 01, 2025 -<br />Dec 31, 2025</td><td>{row.billing}</td><td><b>${row.unit.toFixed(2)}</b><small>{row.source}</small></td><td><Button appearance="subtle" icon={<EditRegular />} aria-label="Edit item" /></td></tr>)}</tbody></table></div>
}

function SideDrawer({ drawer, close, selectedCount, onApply }: { drawer: Drawer; close: () => void; selectedCount: number; onApply: () => void }) {
  const [query, setQuery] = useState('')
  const [selectedProducts, setSelectedProducts] = useState<string[]>([])
  if (drawer === 'none') return null
  const productDrawer = drawer === 'products'; const stepups = drawer === 'stepups'; const bulk = drawer === 'bulk'
  const normalizedQuery = query.trim().toLowerCase()
  const visibleProducts = catalogueProducts.filter(product => !normalizedQuery || [product.name, product.id, product.family].some(value => value.toLowerCase().includes(normalizedQuery)))
  const toggleProduct = (id: string) => setSelectedProducts(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  return <div className="drawer-overlay"><aside className={`side-drawer${productDrawer ? ' catalogue-drawer' : ''}`}><div className="drawer-head"><div><h2>{productDrawer ? 'Add products (Product catalogue)' : stepups ? 'Stepup opportunities' : bulk ? `Edit | ${selectedCount} items selected` : 'Split assistant'}</h2>{productDrawer && <p>Select products to add to this order.</p>}{bulk && <p>Selected line items values will be overwritten.</p>}{stepups && <p>Stepup for JFX-00003 | M365 F3 FUSL Sub Per User</p>}</div><Button appearance="subtle" icon={<DismissRegular />} aria-label="Close" onClick={close} /></div><div className="drawer-body">{productDrawer && <div className="catalogue-content"><Input contentBefore={<SearchRegular />} value={query} onChange={(_, data) => setQuery(data.value)} placeholder="Search by item name, part number/SKU or product family" /><div className="catalogue-toolbar"><span>Filters:</span><Badge appearance="tint">Product family: <b>All</b></Badge><Badge appearance="tint">Offering: <b>All</b></Badge><Button appearance="subtle" icon={<FilterRegular />}>Add filter</Button><span className="table-spacer" /><span>{visibleProducts.length} items</span></div><div className="catalogue-table-wrap"><table className="fluent-table catalogue-table"><thead><tr><th><Checkbox aria-label="Select all products" checked={visibleProducts.length > 0 && visibleProducts.every(product => selectedProducts.includes(product.id))} onChange={(_, data) => setSelectedProducts(data.checked ? visibleProducts.map(product => product.id) : [])} /></th><th>Item name ↓</th><th>Part number / SKU</th><th>Product family</th><th>Offering</th><th>Product type</th><th>Unit price (Source)</th></tr></thead><tbody>{visibleProducts.map(product => <tr key={product.id} className={selectedProducts.includes(product.id) ? 'selected' : ''}><td><Checkbox aria-label={`Select ${product.name}`} checked={selectedProducts.includes(product.id)} onChange={() => toggleProduct(product.id)} /></td><td><span className="product-name"><Mark type={product.icon} /><span><b>{product.name}</b><small>{product.description}</small></span></span></td><td>{product.id}</td><td>{product.family}</td><td>{product.offering}</td><td>{product.type}</td><td><b>${product.unit.toFixed(2)}</b><small>{product.source}</small></td></tr>)}</tbody></table>{visibleProducts.length === 0 && <div className="catalogue-no-results"><SearchRegular /><h3>No products found</h3><p>Try another product name, SKU, or product family.</p></div>}</div></div>}{stepups && <StepupTable />}{bulk && <BulkForm />}</div><div className="drawer-foot"><Button appearance="primary" disabled={productDrawer && !selectedProducts.length} onClick={() => { onApply(); close() }}>{stepups ? 'Add products' : bulk ? 'Apply' : `Add products${selectedProducts.length ? ` (${selectedProducts.length})` : ''}`}</Button><Button onClick={close}>Close</Button></div></aside></div>
}

function StepupTable() { return <table className="fluent-table"><thead><tr><th>Item name ↓</th><th>Part number</th><th>Offering</th><th>Max quantity</th><th>Add quantity</th><th>Unit price (Source)</th><th>Linked base products</th></tr></thead><tbody>{initialProducts.slice(0,4).map(row => <tr key={row.id}><td><span className="product-name"><Mark /><b>{row.name}</b></span></td><td>{row.id}</td><td>Enterprise</td><td>{row.prior + 50}</td><td><Input size="small" type="number" defaultValue="0" /></td><td><b>${row.unit.toFixed(2)}</b><small>{row.source}</small></td><td>⌘</td></tr>)}</tbody></table> }
function BulkForm() { return <div className="bulk-form"><h3>Add quantity</h3><Checkbox label="Add max quantities" /><label>Usage country<Select><option>Select Usage country</option><option>Switzerland</option></Select></label><label>Billing frequency<Select><option>Select Billing frequency</option><option>Annual</option></Select></label><label>Usage start date<Input type="date" /></label><label>Offering<Select><option>Select Offering type</option><option>Enterprise</option></Select></label><label>Subscription term<Select><option>12 months</option></Select></label></div> }

function CartPage({ go }: { go: (view: View) => void }) {
  const [po, setPo] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [split, setSplit] = useState(false)
  return <div className="work-page cart-page"><Breadcrumb items={['Your products', 'Volume licensing', 'Select contract', 'Create order', 'Cart']} /><h1>Create Midterm order for License ID - <Link>7890567890</Link> | Cart</h1><p className="intro">Please enter the purchase order number or name and make sure to review your order and contract details thoroughly before submitting.</p><div className="po-row"><label>PO number / name *<Input value={po} onChange={(_, data) => setPo(data.value)} placeholder="Enter here" /></label><span>or</span><Checkbox label="Use license ID as PO number (7890567890)" onChange={(_, data) => data.checked && setPo('7890567890')} /></div><div className="command-row"><Button appearance="subtle" icon={<PaymentRegular />}>Move to different PO</Button><Button appearance="subtle" icon={<ArrowDownloadRegular />}>Download quote</Button><Button appearance="subtle" onClick={() => setSplit(true)}>⌘ Split assistant <ChevronDownRegular /></Button><Button appearance="subtle">▦ View Payment Schedule</Button><span className="table-spacer" /><span>10 items</span><Input size="small" contentBefore={<SearchRegular />} placeholder="Search" /></div>{split && <div className="split-assistant"><h3>How would you like your cart products to be split?</h3><p>Now create multiple orders from your cart on a predefined format.</p><Checkbox label="Split selected items as per reservation PO number" /><Checkbox label="Custom split" /><Button appearance="primary" onClick={() => setSplit(false)}>Split order</Button></div>}<CartTable selected={selected} setSelected={setSelected} /><div className="sticky-actions"><Button onClick={() => go('workspace')}>Back</Button><Button>Save as draft</Button><Button appearance="primary" disabled={!po} onClick={() => go('orderSuccess')}>Submit Order</Button><div className="estimated">Total estimated amount (10 items): <b>$355,024.45</b></div></div></div>
}

function CartTable({ selected, setSelected }: { selected: string[]; setSelected: (ids: string[]) => void }) { return <div className="table-scroll"><table className="fluent-table cart-table"><thead><tr><th></th><th>Item name</th><th>Part number</th><th>Program offering</th><th>Product type</th><th>Prior quantity</th><th>Additional quantity</th><th>Total quantity</th><th>Usage country</th><th>Billing option</th><th>Usage date</th><th>Coverage start date</th><th>Coverage end date</th><th>Net unit price</th><th>Extended amount</th></tr></thead><tbody>{cartRows.map(row => <tr key={row[1]} className={selected.includes(row[1]) ? 'selected' : ''}><td><Checkbox checked={selected.includes(row[1])} onChange={() => setSelected(selected.includes(row[1]) ? selected.filter(id => id !== row[1]) : [...selected, row[1]])} /></td><td><span className="product-name"><Mark /><b>{row[0]}</b></span></td><td>{row[1]}</td><td>ACP</td><td>True-up<small>Online subscription</small></td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td>Switzerland</td><td>Annual</td><td>Jan 01, 2025</td><td>Jan 06, 2025</td><td>Jul 31, 2025</td><td>{row[5]}<small>CPS: 98765.002</small></td><td><b>{row[6]}</b></td></tr>)}</tbody></table></div> }

function SuccessPane({ reservation, go }: { reservation?: boolean; go: (view: View) => void }) { return <div className="success-overlay"><div className="success-pane"><CheckmarkCircleRegular /><h2>{reservation ? 'Reservation placed successfully!' : 'Your order(s) are being processed.'}</h2><p>{reservation ? 'Here is a quick summary of your reservation.' : 'You can check the latest status of your order(s) here.'}</p>{reservation ? <div className="success-summary"><Link>Download confirmation details</Link><dl><dt>Reservation ID</dt><dd>200124987</dd><dt>Reservation date</dt><dd>Aug 2025</dd><dt>Usage country</dt><dd>Switzerland</dd><dt>Total estimated amount</dt><dd>$18,318.90</dd></dl></div> : <p>Feel free to exit the flow by clicking on any button below.</p>}<div className="success-buttons"><Button appearance="primary" onClick={() => go(reservation ? 'reservations' : 'orders')}>{reservation ? 'View all reservations' : 'View all orders'}</Button><Button onClick={() => go(reservation ? 'reservationCreate' : 'contracts')}>{reservation ? 'Reserve another' : 'Create another order'}</Button></div></div></div> }

function OrdersPage({ go }: { go: (view: View) => void }) {
  const [manage, setManage] = useState(false)
  return <div className="wide-page"><Breadcrumb items={['Your products', 'Volume licensing', 'Orders']} /><h1>Orders</h1><p className="intro">This serves as confirmation of orders we have received under all your contracts. You should refer to your license agreement for guidance.</p><div className="contract-view"><b>Contract view</b><span>Products connected to: 6021478465</span><Link onClick={() => setManage(true)}>Change contract</Link></div><MessageBar intent="warning"><MessageBarBody>This contract is currently in the compliance window. Please place the anniversary order.</MessageBarBody><Button size="small">View details</Button></MessageBar><div className="command-row"><Button appearance="subtle" icon={<ArrowDownloadRegular />}>Export to Excel</Button><Button appearance="subtle" icon={<FilterRegular />}>Add filter</Button><span className="table-spacer" /><Input size="small" contentBefore={<SearchRegular />} placeholder="Search" /></div><table className="fluent-table"><thead><tr><th>Order number</th><th>Status</th><th>Usage start date</th><th>Ordered on ↓</th><th>Ordered by</th><th>Organization name</th><th>Sales location</th></tr></thead><tbody>{contracts.map((row, index) => <tr key={row[0]} onClick={() => go('orderDetail')}><td><Link>{index ? `PO${83643 + index}` : '1234567890'}</Link></td><td><Status state={index % 3 === 0 ? 'Processed' : index % 3 === 1 ? 'In review' : 'Failed'} /></td><td>Sep 01, 2025</td><td>Aug {10 + index}, 2025</td><td>Admin@proseware.com</td><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table>{manage && <ManageContractDrawer close={() => setManage(false)} />}</div>
}

function Status({ state }: { state: string }) { return <span className={`state state-${state.toLowerCase().replaceAll(' ', '-')}`}><i />{state}</span> }
function ManageContractDrawer({ close }: { close: () => void }) { return <div className="drawer-overlay"><aside className="side-drawer manage"><div className="drawer-head"><div><h2>Select contract</h2><p>Select a contract to view its orders.</p><Link>Learn more about contracts</Link></div><Button appearance="subtle" icon={<DismissRegular />} onClick={close} /></div><div className="drawer-body"><label>Search contracts<Input placeholder="Enter contract" /></label><table className="fluent-table"><thead><tr><th></th><th>License ID ↓</th><th>Organization</th><th>Sales location</th><th>Compliance window</th><th>Status</th></tr></thead><tbody>{contracts.slice(0,5).map(row => <tr key={row[0]}><td><Checkbox /></td><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td></tr>)}</tbody></table></div><div className="drawer-foot"><Button appearance="primary" disabled>View orders</Button><Button onClick={close}>Close</Button></div></aside></div> }

function OrderDetailPage({ go }: { go: (view: View) => void }) { return <div className="wide-page"><Breadcrumb items={['Your products', 'Volume licensing', 'Orders', 'Purchase order: 1234567890']} /><Button appearance="subtle" onClick={() => go('orders')}>← Back</Button><h1>Purchase order : 1234567890</h1><div className="order-meta"><Status state="Processed" /><span>CPS ID<br /><b>98765.003</b></span><span>License ID<br /><b>6021478465</b></span><span>Program<br /><b>Enterprise</b></span><span>Country<br /><b>US</b></span></div><TabList defaultSelectedValue="summary"><Tab value="summary">Summary</Tab><Tab value="invoice">Invoices and billing schedule</Tab></TabList><div className="command-row"><Button appearance="subtle" icon={<ArrowDownloadRegular />}>Export to Excel</Button><span className="table-spacer" /><span>2 items</span><Input size="small" contentBefore={<SearchRegular />} placeholder="Search" /></div><table className="fluent-table"><thead><tr><th>Item name</th><th>Part number</th><th>Product type</th><th>Quantity</th><th>Unit price</th><th>Unit type</th><th>Extended amount</th><th>Billing frequency</th><th>Usage country</th><th>Coverage period</th></tr></thead><tbody>{cartRows.slice(0,2).map(row => <tr key={row[1]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>True-up</td><td>{row[4]}</td><td>{row[5]}</td><td>Month</td><td>{row[6]}</td><td>Annual</td><td>Canada</td><td>2025</td></tr>)}</tbody></table></div> }

function ReservationsPage({ go }: { go: (view: View) => void }) { return <div className="wide-page"><Breadcrumb items={['Your products', 'Volume licensing', 'View reservations']} /><div className="title-line"><h1>Reservations</h1><span>Last updated on <b>12th Jan, 2023</b></span></div><p className="intro">These are additional services that Microsoft provides to start using online services immediately, with the license purchase confirmed at a later date, typically during the annual true-up process.</p><div className="contract-view"><b>Contract view</b><span>Products connected to: 6021478465</span><Link>Change contract</Link></div><div className="command-row"><Button appearance="subtle" icon={<ArrowDownloadRegular />}>Export to Excel</Button><Button appearance="subtle" icon={<AddRegular />} onClick={() => go('reservationCreate')}>Reserve a new online service</Button><span className="table-spacer" /><span>8 reservations</span><Button appearance="subtle" icon={<FilterRegular />}>Filter</Button><Input size="small" contentBefore={<SearchRegular />} placeholder="Search by reservation/license" /></div><div className="filter-row left"><span>Filters:</span><Badge appearance="tint">Reservation: <b>All</b></Badge><Badge appearance="tint">Reservation Date: <b>All</b></Badge><Badge appearance="tint">Status: <b>All</b></Badge><Button appearance="subtle" icon={<FilterRegular />}>Add filter</Button></div><table className="fluent-table"><thead><tr><th></th><th>Reservation ID ↑</th><th>Reservation date</th><th>Usage start date</th><th>Reservation status</th><th>Reconciliation status</th><th>Requestor</th><th>Reconciliation order number</th><th>Cancel</th></tr></thead><tbody>{reservationRows.map((row, index) => <tr key={`${row[0]}-${index}`}><td><Checkbox /></td><td><b>{row[0]}</b><small>{row[1]}</small></td><td>{row[2]}</td><td>{row[3]}</td><td><Status state={row[4]} /></td><td>{row[5] === '-' ? '-' : <Status state={row[5]} />}</td><td>{row[6]}</td><td><Link>{row[7]}</Link></td><td><Link>{row[8]}</Link></td></tr>)}</tbody></table></div> }

function ReservationCreatePage({ go }: { go: (view: View) => void }) {
  const [picker, setPicker] = useState(false); const [selected, setSelected] = useState<string[]>([])
  return <div className="wide-page reservation-create"><Breadcrumb items={['Your products', 'Volume licensing', 'Make a new reservation']} /><h1>Make a new reservation</h1><p className="intro">Select online services to reserve and start using immediately.</p><div className="reservation-form"><label>Commit to make reservation for<Select defaultValue="6021478465"><option value="6021478465">License ID: 6021478465</option></Select></label><label>Usage start date<Input type="date" defaultValue="2025-08-01" /></label></div><h2>Selected online services</h2><Button appearance="subtle" icon={<AddRegular />} onClick={() => setPicker(true)}>Add services</Button><table className="fluent-table"><thead><tr><th>Service name</th><th>Part number</th><th>Quantity</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>{selected.map((id, index) => <tr key={id}><td>{initialProducts[index].name}</td><td>{id}</td><td><Input size="small" defaultValue="10" /></td><td>${initialProducts[index].unit.toFixed(2)}</td><td>${(initialProducts[index].unit * 10).toFixed(2)}</td></tr>)}</tbody></table><div className="sticky-actions"><Button appearance="primary" disabled={!selected.length} onClick={() => go('reservationSuccess')}>Submit reservation</Button><Button onClick={() => go('products')}>Cancel</Button></div>{picker && <div className="drawer-overlay"><aside className="side-drawer service-picker"><div className="drawer-head"><div><h2>View and add online services</h2><p>Here is the list of services you can reserve for your contract</p></div><Button appearance="subtle" icon={<DismissRegular />} onClick={() => setPicker(false)} /></div><div className="drawer-body"><Input contentBefore={<SearchRegular />} placeholder="Search any product, SKU, product description" /><MessageBar intent="warning"><MessageBarBody>Some online services you selected may be reconciled in the portal.</MessageBarBody></MessageBar><table className="fluent-table"><thead><tr><th></th><th>Service name</th><th>Item name</th><th>Part number</th><th>Unit price</th><th>Description</th></tr></thead><tbody>{initialProducts.slice(0,6).map(row => <tr key={row.id}><td><Checkbox checked={selected.includes(row.id)} onChange={() => setSelected(current => current.includes(row.id) ? current.filter(id => id !== row.id) : [...current, row.id])} /></td><td>{row.name}</td><td>License span</td><td>{row.id}</td><td>${row.unit.toFixed(2)}</td><td>Reserve licenses now and purchase them later.</td></tr>)}</tbody></table></div><div className="drawer-foot"><Button appearance="primary" disabled={!selected.length} onClick={() => setPicker(false)}>Add services</Button><Button onClick={() => setPicker(false)}>Cancel</Button></div></aside></div>}</div>
}

function App() {
  const [view, setView] = useState<View>('products')
  const [version, setVersion] = useState<Version>('v1')
  let page: React.ReactNode
  if (view === 'products') page = version === 'v3' ? <V3OrderHub go={setView} /> : <ProductsPage go={setView} />
  else if (view === 'contracts') page = <ContractsPage go={setView} />
  else if (view === 'workspace') page = <WorkspacePage go={setView} />
  else if (view === 'cart') page = <CartPage go={setView} />
  else if (view === 'orderSuccess') page = <><CartPage go={setView} /><SuccessPane go={setView} /></>
  else if (view === 'orders') page = <OrdersPage go={setView} />
  else if (view === 'orderDetail') page = <OrderDetailPage go={setView} />
  else if (view === 'reservations') page = <ReservationsPage go={setView} />
  else if (view === 'reservationCreate') page = <ReservationCreatePage go={setView} />
  else page = <><ReservationCreatePage go={setView} /><SuccessPane reservation go={setView} /></>
  return <FluentProvider theme={webLightTheme}><AdminShell view={view} setView={setView} version={version} setVersion={setVersion}>{page}</AdminShell></FluentProvider>
}

export default App